default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: bevyhr_development
  port: 5432
  username: rails
  password: rails

development:
  primary:
    <<: *default
    database: bevyhr_development
  queue:
    <<: *default
    database: bevyhr_development_queue

test:
  <<: *default
  database: bevyhr_test

# Store production database in PostgreSQL
production:
  primary: &production_primary
    <<: *default
    database: <%= ENV["POSTGRES_DB"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
  cache: &production_cache
    <<: *default
    database: bevyhr_production_cache
  queue: &production_queue
    <<: *default
    database: bevyhr_production_queue
  cable: &production_cable
    <<: *default
    database: bevyhr_production_cable
