default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: rails
  password: rails

development:
  primary:
    <<: *default
    database: bevyhr_development
  queue:
    <<: *default
    database: bevyhr_development_queue

test:
  <<: *default
  database: bevyhr_test

# Store production database in PostgreSQL
production:
  primary:
    <<: *default
    database: <%= ENV["POSTGRES_DATABASE"] %>
    username: <%= ENV["POSTGRES_USERNAME"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV["POSTGRES_HOST"] %>

  cache:
    <<: *default
    database: bevyhr_production_cache
  queue:
    <<: *default
    database: bevyhr_production_queue
  cable:
    <<: *default
    database: bevyhr_production_cable
